{{- if .Values.services.gateway.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "eidf-crm.fullname" . }}-gateway
  labels:
    {{- include "eidf-crm.labels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
spec:
  {{- if not .Values.services.gateway.autoscaling.enabled }}
  replicas: {{ .Values.services.gateway.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "eidf-crm.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: gateway
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
      labels:
        {{- include "eidf-crm.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: gateway
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "eidf-crm.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: gateway
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}/{{ .Values.services.gateway.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.services.gateway.service.targetPort }}
              protocol: TCP
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: {{ include "eidf-crm.fullname" . }}
                  key: nodeEnv
            - name: PORT
              value: "{{ .Values.services.gateway.service.targetPort }}"
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "eidf-crm.fullname" . }}
                  key: logLevel
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "eidf-crm.fullname" . }}
                  key: jwtSecret
            - name: AUTH_SERVICE_URL
              value: "http://{{ include "eidf-crm.fullname" . }}-auth:3001"
            - name: ORGANIZATION_SERVICE_URL
              value: "http://{{ include "eidf-crm.fullname" . }}-organization:3002"
            - name: WOOCOMMERCE_SERVICE_URL
              value: "http://{{ include "eidf-crm.fullname" . }}-woocommerce:3003"
            - name: BILLING_SERVICE_URL
              value: "http://{{ include "eidf-crm.fullname" . }}-billing:3004"
            - name: ANALYTICS_SERVICE_URL
              value: "http://{{ include "eidf-crm.fullname" . }}-analytics:3005"
            - name: AI_SERVICE_URL
              value: "http://{{ include "eidf-crm.fullname" . }}-ai:3006"
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.services.gateway.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}