apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: eidf-crm
  labels:
    app: gateway
    tier: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
        tier: api
    spec:
      containers:
      - name: gateway
        image: eidf-crm/gateway:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: jwt-secret
        - name: AUTH_SERVICE_URL
          value: "http://auth-service:3001"
        - name: ORGANIZATION_SERVICE_URL
          value: "http://organization-service:3002"
        - name: WOOCOMMERCE_SERVICE_URL
          value: "http://woocommerce-service:3003"
        - name: BILLING_SERVICE_URL
          value: "http://billing-service:3004"
        - name: ANALYTICS_SERVICE_URL
          value: "http://analytics-service:3005"
        - name: AI_SERVICE_URL
          value: "http://ai-service:3006"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: eidf-crm
  labels:
    app: gateway
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: gateway